# 1. Utilise PHP avec FPM
FROM php:8.2-fpm

# 2. Installe les dépendances système
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libzip-dev \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    sqlite3 \
    libsqlite3-dev \
    && docker-php-ext-install pdo pdo_mysql zip

# 3. Installe Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 4. Crée le dossier de travail
WORKDIR /var/www

# 5. Copie les fichiers de ton projet
COPY . .

# 6. Installe les dépendances PHP de Laravel
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Copie le .env.example
COPY .env.example .env

# 8. Génére la clé de l'app
RUN php artisan key:generate

# 9. Donne les permissions nécessaires
RUN chown -R www-data:www-data storage bootstrap/cache

# 10. Expose le port que Laravel utilise
EXPOSE 8000

# 11. Lancement de l'app Laravel
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
