# Utilise PHP avec FPM
FROM php:8.2-fpm

# Installe les dépendances système
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libzip-dev \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    sqlite3 \
    libsqlite3-dev \
    && docker-php-ext-install pdo pdo_mysql zip

# Installe Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Crée le dossier de travail
WORKDIR /var/www

# Copie les fichiers de ton projet
COPY . .

# Installe les dépendances PHP de Laravel
RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Donne les permissions nécessaires
RUN chown -R www-data:www-data storage bootstrap/cache

# Expose le port que Laravel utilise
EXPOSE 8000

# Lancement de l'app Laravel
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
